//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 09:49:17 AM EET 
//


package fi.vaylavirasto.sillari.service.fim.responseModel;

import lombok.ToString;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for groupType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="groupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObjectKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="persons" type="{}personsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "groupType", propOrder = {
        "objectKey",
        "objectID",
        "displayName",
        "persons"
})
@ToString
public class GroupType {

    @XmlElement(name = "ObjectKey", required = true)
    protected String objectKey;
    @XmlElement(name = "ObjectID", required = true)
    protected String objectID;
    @XmlElement(name = "DisplayName", required = true)
    protected String displayName;
    @XmlElement(required = true)
    protected PersonsType persons;

    /**
     * Gets the value of the objectKey property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getObjectKey() {
        return objectKey;
    }

    /**
     * Sets the value of the objectKey property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setObjectKey(String value) {
        this.objectKey = value;
    }

    /**
     * Gets the value of the objectID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getObjectID() {
        return objectID;
    }

    /**
     * Sets the value of the objectID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setObjectID(String value) {
        this.objectID = value;
    }

    /**
     * Gets the value of the displayName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the persons property.
     *
     * @return possible object is
     * {@link PersonsType }
     */
    public PersonsType getPersons() {
        return persons;
    }

    /**
     * Sets the value of the persons property.
     *
     * @param value allowed object is
     *              {@link PersonsType }
     */
    public void setPersons(PersonsType value) {
        this.persons = value;
    }

}
