sillari:
  wmts:
    url: https://api.vayla.fi/rasteripalvelu-mml/wmts/maasto/1.0.0/
  geoserver:
    url: https://sillaripreprod.testivaylapilvi.fi/geoserver/
  lelu:
    version: @leluApiVersion@
    routeuploadpath: /tmp
  trex:
    url: https://api.vayla.fi/trex/rajapinta/taitorakenne/v2/yleistiedot/silta
    pic-url: https://api.vayla.fi/trex/rajapinta/rakennekuva-api/v1/
    pic-bin-path: yleiskuva
    pic-info-path: kuvatiedot
    username: ${FIM_USERNAME}
    password: ${FIM_PASSWORD}
  fim:
    url: https://api.vayla.fi/FIMGET/SimpleREST4FIM/1/group.svc/getGroup2?displayName=sillari_sillanvalvoja
    username: ${FIM_USERNAME}
    password: ${FIM_PASSWORD}
  amazoncognito:
    url: https://sillaritest.auth.eu-west-1.amazoncognito.com
    clientId: 152i189u2cu0cae9dpg6am44b6
    redirectUrl: https://sillaritest.testivaylapilvi.fi
spring:
  application:
    name: SillaRi
  datasource:
    # Values from pom.xml profile properties
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  flyway:
    enabled: true
    baselineOnMigrate: true
logging:
  config: classpath:log4j2-test.xml
server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  servlet: # 2.0
    context-path: /api
management:
  contextPath: /actuator
  security:
    enabled: false
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
  health:
    jms:
      enabled: false
  info:
    git:
      mode: full
endpoints:
  prometheus:
    enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operationsSorter: alpha
    tagsSorter: alpha
  show-actuator: true
  version: 3.0
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: api
      packagesToScan: fi.vaylavirasto.sillari.api
