spring:
  application:
    name: SillaRi
  datasource:
    # Values from pom.xml profile properties
    url: @db.url@
    username: @db.username@
    password: @db.password@
    driver-class-name: @db.driver@
  jooq:
    sql-dialect: POSTGRES
  flyway:
    enabled: true
    baselineOnMigrate: true
logging:
  config: classpath:log4j2-dev.xml
graphql:
  servlet:
    enabled: true
    mapping: "/graphql"
    corsEnabled: true
server:
  port: 8080
  servlet: # 2.0
    context-path: /api
management:
  contextPath: /actuator
  security:
    enabled: false
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
  health:
    jms:
      enabled: false
  info:
    git:
      mode: full
endpoints:
  prometheus:
    enabled: true
