spring:
  application:
    name: SillaRi
  datasource:
    url: "jdbc:postgresql://localhost:5432/sillari"
    username: sillari
    password: sillari1234
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect:postgres
  h2:
    console:
      enabled: true
      path: "/h2"
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baselineOnMigrate: true
    url: "jdbc:postgresql://localhost:5432/sillari"
    username: sillari
    password: sillari1234
graphql:
  servlet:
    enabled: true
    mapping: "/graphql"
    corsEnabled: true
