spring:
  application:
    name: SillaRi
  datasource:
    url: "jdbc:postgresql://sillari-dev.cpakz3z86ezw.eu-west-1.rds.amazonaws.com:5432/sillari"
    username: sillari
    password: silLari1234B7
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect:postgres
  h2:
    console:
      enabled: true
      path: "/h2"
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baselineOnMigrate: true
    url: "jdbc:postgresql://sillari-dev.cpakz3z86ezw.eu-west-1.rds.amazonaws.com:5432/sillari"
    username: sillari
    password: silLari1234B7
graphql:
  servlet:
    enabled: true
    mapping: "/graphql"
    corsEnabled: true
server:
  port: 8080

management:
  contextPath: /actuator
  security:
    enabled: false
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
  health:
    jms:
      enabled: false
  info:
    git:
      mode: full
endpoints:
  prometheus:
    enabled: true

