sillari:
  wmts:
    url: https://oag.vayla.fi/rasteripalvelu-mml/wmts/maasto/1.0.0/
  geoserver:
    url: https://sillaridev.testivaylapilvi.fi/geoserver/
  lelu:
    version: @project.version@
spring:
  application:
    name: SillaRi
  datasource:
    # Values from pom.xml profile properties
    url: @db.url@
    username: @db.username@
    password: @db.password@
    driver-class-name: @db.driver@
  jooq:
    sql-dialect: POSTGRES
  flyway:
    enabled: true
    baselineOnMigrate: true
logging:
  config: classpath:log4j2-dev.xml
graphql:
  servlet:
    enabled: true
    mapping: "/graphql"
    corsEnabled: true
server:
  port: 8080
  servlet: # 2.0
    context-path: /api
management:
  contextPath: /actuator
  security:
    enabled: false
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
  health:
    jms:
      enabled: false
  info:
    git:
      mode: full
endpoints:
  prometheus:
    enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operationsSorter: alpha
    tagsSorter: alpha
  show-actuator: true
  version: 3.0
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: api
      packagesToScan: fi.vaylavirasto.sillari.api
