spring:
  application:
    name: SillaRi
  datasource:
    url: "jdbc:postgresql://localhost:5432/sillari"
    username: sillari
    password: sillari1234
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect:postgres
  h2:
    console:
      enabled: true
      path: "/h2"
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baselineOnMigrate: true
    url: "jdbc:postgresql://localhost:5432/sillari"
    username: sillari
    password: sillari1234
graphql:
  servlet:
    enabled: true
    mapping: "/graphql"
    corsEnabled: true

server:
  port: 8080
  servlet: # 2.0
    context-path: /api

management:
  contextPath: /actuator
  security:
    enabled: false
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
  health:
    jms:
      enabled: false
  info:
    git:
      mode: full
endpoints:
  prometheus:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  show-actuator: true
  version: 3.0
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: api
      packagesToScan: fi.vaylavirasto.sillari.api