sillari:
  wmts:
    url: https://testiapi.vayla.fi/rasteripalvelu-mml/wmts/maasto/1.0.0/
  geoserver:
    url: http://sillari-geoserver:8080/geoserver/
  lelu:
    version: @leluApiVersion@
    routeuploadpath: /tmp
  trex:
    url: http://localhost:8080/api/devtools/localHardCodedBridgeInfoJson
    pic-url: http://localhost:8080/api/devtools/localHardCodedPicJson/
    pic-bin-path: yleiskuva
    pic-info-path: kuvatiedot
    username: na
    password: na
  fim:
    url: http://localhost:8080/api/devtools/localHardCodedSupervisors
    #url: https://testiapi.vayla.fi/FIMGET/SimpleREST4FIM/1/group.svc/getGroup2?displayName=sillari_sillanvalvoja
    username: ${FIM_USERNAME}
    password: ${FIM_PASSWORD}
  amazoncognito:
    url: http://localhost:3000
    clientId: na
    redirectUrl: http://localhost:3000
spring:
  application:
    name: SillaRi
  datasource:
    # Values from pom.xml profile properties
    url: @db.url@
    username: @db.username@
    password: @db.password@
    driver-class-name: @db.driver@
  jooq:
    sql-dialect: POSTGRES
  flyway:
    enabled: true
    baselineOnMigrate: true
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  servlet: # 2.0
    context-path: /api
management:
  contextPath: /actuator
  security:
    enabled: false
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
  health:
    jms:
      enabled: false
  info:
    git:
      mode: full
endpoints:
  prometheus:
    enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operationsSorter: alpha
    tagsSorter: alpha
  show-actuator: true
  version: 3.0
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: api
      packagesToScan: fi.vaylavirasto.sillari.api
