spring:
  application:
    name: Sillari UI
server:
  port: 8095
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,image/svg+xml,application/x-font-ttf
    min-response-size: 1024
  servlet:
    context-path: /
