version: "3"
services:
  sillari-backend:
    hostname: sillari-backend
    build:
      context: ./sillari-backend
      dockerfile: Dockerfile_local
    environment:
      - environment=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sillari-local-db:5432/sillari
      - FIM_USERNAME=<insert_here>
      - FIM_PASSWORD=<insert_here>
    ports:
      - 8080:8080
    depends_on:
      - sillari-local-db
  sillari-ui:
    hostname: sillari-ui
    build:
      context: ./sillari-ui
      dockerfile: Dockerfile_local
    ports:
      - 3000:8095
  sillari-geoserver:
    hostname: sillari-geoserver
    build:
      context: ./geoserver
      dockerfile: Dockerfile_local
    ports:
      - 8081:8080
    depends_on:
      - sillari-local-db
  sillari-local-db:
    hostname: sillari-local-db
    build:
      context: ./sillari-local-db
    environment:
      - POSTGRES_DB=sillari
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./sillari-local-db/pgdata:/pgdata
