FROM 384409174079.dkr.ecr.eu-west-1.amazonaws.com/geoserver
MAINTAINER Jari Piitulainen <jari.piitulainen@cgi.com>
#CMD mkdir /configs
#ADD conf/server.xml /configs/server.xml
#ADD conf/web.xml /configs/web.xml
#ADD conf/context.xml /configs/context.xml
#CMD chmod gou+rw /configs/server.xml
#CMD chmod gou+rw /configs/web.xml
#CMD chmod gou+rw /configs/context.xml
#ADD startgeoserver.sh /startgeoserver.sh
#RUN chmod gou+rx /startgeoserver.sh
#CMD cp /configs/server.xml /usr/local/tomcat/conf/config.xml
#CMD mv /usr/local/tomcat/conf /usr/local/tomcat/conf-old
#CMD ln -s /opt/geoserver/config/tomcat/conf /usr/local/tomcat/conf
#CMD mv /usr/local/tomcat/webapps /usr/local/tomcat/webapps-old
#CMD ln -s /opt/geoserver/config/webapps /usr/local/tomcat/webapps
#CMD chown geoserveruser.geoserverusers /usr/local/tomcat/conf
#CMD chown geoserveruser.geoserverusers /usr/local/tomcat/webapps
#CMD mkdir /config
#ADD conf/server.xml /config/server.xml
#CMD cp /config/server.xml /usr/local/tomcat/conf/server.xml
#ENV GEOSERVER_ADMIN_USER admin
#ENV GEOSERVER_ADMIN_PASSWORD admin12345!
#ENTRYPOINT ["/startgeoserver.sh"]
